database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5406:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: bbga
    POSTGRES_USER: bbga

web:
  build: ./web
  ports:
    - "8102:8000"
  links:
    - database:database
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    DB_NAME: bbga
    DB_PASSWORD: insecure
