version: '3.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5406:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bbga
      POSTGRES_USER: bbga

  web:
    build: ./web
    ports:
      - "8000"
    links:
      - database:database
    volumes:
      - $PWD/data:/app/data
    environment:
      SECRET_KEY: hoi
      DB_NAME: bbga
      DB_USER: bbga
      DB_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "bbga.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
